default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>

development:
  <<: *default
  database: facebook_development

test:
  <<: *default
  database: facebook_test

production:
  <<: *default
  database: facebook_production
  username: <%= ENV["FACEBOOK_DATABASE_USER"] %>
  password: <%= ENV["FACEBOOK_DATABASE_PASSWORD"] %>
  host: <%= ENV['DATABASE_HOST'] %>
  # Optional: If using DATABASE_URL for production
  url: <%= ENV["DATABASE_URL"] %>
